repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.83.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.7
    hooks:
    -   id: ripsecrets
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
